# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: .github
# Semantic versioning is used d=for this plugin: https://semver.org/
version-template: $MAJOR.$MINOR.$PATCH
tag-template: trilead-api-$NEXT_PATCH_VERSION
name-template: $NEXT_PATCH_VERSION
